# Generated by Django 6.0.3 on 2026-07-28 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Order Number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('MEASUREMENT', 'Pending Measurement'), ('IN_PRODUCTION', 'In Production'), ('READY', 'Ready for Ship'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('note', models.TextField(blank=True, verbose_name='General Order Note')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItemsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2nd Floor Doors', max_length=100, verbose_name='Group Name/Label')),
                ('is_custom_front', models.BooleanField(default=False, verbose_name='Is Custom Front')),
                ('custom_front_name', models.CharField(blank=True, max_length=255, verbose_name='Custom Front Ref')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Items Quantity in Group')),
                ('has_window', models.BooleanField(default=False, verbose_name='Has Glass/Bathroom Window')),
                ('engraving_code', models.CharField(blank=True, max_length=100, verbose_name='Engraving Pattern / Code')),
                ('group_custom_params', models.JSONField(blank=True, default=dict, verbose_name='Additional Group Parameters')),
                ('front', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_groups', to='catalog.front', verbose_name='Catalog Front')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_groups', to='catalog.product', verbose_name='Product Model')),
            ],
            options={
                'verbose_name': 'Order Items Group',
                'verbose_name_plural': 'Order Items Groups',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_label', models.CharField(blank=True, help_text='e.g., Bathroom, Bedroom 1', max_length=100, verbose_name='Item Tag/Room')),
                ('position_number', models.PositiveIntegerField(db_index=True, verbose_name='Item Number in Order')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Height (H), mm')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Width (W), mm')),
                ('wall_thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Wall Thickness, mm')),
                ('opening_direction', models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=10, verbose_name='Opening Direction')),
                ('opening_type', models.CharField(blank=True, choices=[('OUTWARD', 'Outward'), ('INWARD', 'Inward')], max_length=10, verbose_name='Opening Type')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Measurer / Production Note')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderitemsgroup', verbose_name='Order Group')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
