# Generated by Django 6.0.3 on 2026-08-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.AddField(
            model_name='order',
            name='color_frames',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет коробок'),
        ),
        migrations.AddField(
            model_name='order',
            name='color_panels',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет панелей (полотна)'),
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='order',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заказчик / Клиент'),
        ),
        migrations.AddField(
            model_name='order',
            name='front',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фронт / Отделка'),
        ),
        migrations.AddField(
            model_name='order',
            name='painting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата покраски'),
        ),
        migrations.AddField(
            model_name='order',
            name='series',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан в системе'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, help_text='Уникальный номер (например, ORD-2026-001)', max_length=50, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('MEASUREMENT', 'Pending Measurement'), ('IN_PRODUCTION', 'In Production'), ('READY', 'Ready for Ship'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
