# Generated by Django 6.0.3 on 2026-08-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_product_productmodel_customizer'),
        ('orders', '0002_alter_order_options_remove_order_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemsgroup',
            options={'ordering': ['id'], 'verbose_name': 'Группа элементов заказа', 'verbose_name_plural': 'Группы элементов заказа'},
        ),
        migrations.RemoveField(
            model_name='orderitemsgroup',
            name='custom_front_name',
        ),
        migrations.RemoveField(
            model_name='orderitemsgroup',
            name='engraving_code',
        ),
        migrations.RemoveField(
            model_name='orderitemsgroup',
            name='group_custom_params',
        ),
        migrations.RemoveField(
            model_name='orderitemsgroup',
            name='has_window',
        ),
        migrations.RemoveField(
            model_name='orderitemsgroup',
            name='is_custom_front',
        ),
        migrations.RemoveField(
            model_name='orderitemsgroup',
            name='name',
        ),
        migrations.AddField(
            model_name='orderitemsgroup',
            name='color_frames',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет коробок'),
        ),
        migrations.AddField(
            model_name='orderitemsgroup',
            name='color_panels',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет панелей (полотна)'),
        ),
        migrations.AddField(
            model_name='orderitemsgroup',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='orderitemsgroup',
            name='is_split_installation',
            field=models.BooleanField(default=False, help_text='True = косяк и полотно в разные даты, False = одновременно', verbose_name='Раздельный монтаж'),
        ),
        migrations.AddField(
            model_name='orderitemsgroup',
            name='series',
            field=models.CharField(blank=True, help_text='Если пусто — подтянется из Заказа', max_length=100, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='front',
            field=models.CharField(blank=True, help_text='Если пусто — подтянется из Заказа', max_length=100, null=True, verbose_name='Фронт / Отделка'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_groups', to='catalog.productmodel', verbose_name='Модель изделия'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Количество одинаковых изделий (дверей) в этой группе', verbose_name='Количество в группе'),
        ),
        migrations.AlterModelTable(
            name='orderitemsgroup',
            table='order_items_groups',
        ),
    ]
