# Generated by Django 6.0.3 on 2026-08-03 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitemsgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id'], 'verbose_name': 'Изделие заказа', 'verbose_name_plural': 'Изделия заказа'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_label',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='note',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='opening_direction',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='opening_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='position_number',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='wall_thickness',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='addition_cut',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительный вырез / подрезка'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к изделию'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_hinge1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Высота петли 1 (мм)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_hinge2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Высота петли 2 (мм)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_hinge3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Высота петли 3 (мм)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_hinge4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Высота петли 4 (мм)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_hinge5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Высота петли 5 (мм)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_lock_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Кастомная высота замка (мм)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='direction',
            field=models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=10, null=True, verbose_name='Направление открывания'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='opening',
            field=models.CharField(blank=True, choices=[('LEFT', 'Левое (L)'), ('RIGHT', 'Правое (R)')], max_length=10, null=True, verbose_name='Сторона открывания'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место установки (Этаж / Ось / Помещение)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='wall',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Толщина стены / проема (мм)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderitemsgroup', verbose_name='Группа элементов'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота (мм)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина (мм)'),
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
    ]
