# Generated by Django 6.0.3 on 2026-08-05 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_customizer_options_alter_front_options_and_more'),
        ('orders', '0004_alter_orderitem_options_remove_orderitem_item_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'הזמנה', 'verbose_name_plural': 'הזמנות'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id'], 'verbose_name': 'פריט הזמנה', 'verbose_name_plural': 'פריטי הזמנה'},
        ),
        migrations.AlterModelOptions(
            name='orderitemsgroup',
            options={'ordering': ['id'], 'verbose_name': 'קבוצת פריטי הזמנה', 'verbose_name_plural': 'קבוצות פריטי הזמנה'},
        ),
        migrations.AlterField(
            model_name='order',
            name='color_frames',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע משקופים'),
        ),
        migrations.AlterField(
            model_name='order',
            name='color_panels',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע פנלים (כנף)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך סיום'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='נוצר במערכת'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='לקוח'),
        ),
        migrations.AlterField(
            model_name='order',
            name='front',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.front', verbose_name='חזית / גימור'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, help_text='מספר ייחודי (למשל ORD-2026-001)', max_length=50, unique=True, verbose_name='מספר הזמנה'),
        ),
        migrations.AlterField(
            model_name='order',
            name='painting_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך צביעה'),
        ),
        migrations.AlterField(
            model_name='order',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.series', verbose_name='סדרה'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='תאריך התחלה'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'טיוטה'), ('MEASUREMENT', 'ממתין למדידה'), ('IN_PRODUCTION', 'בייצור'), ('READY', 'מוכן למשלוח'), ('COMPLETED', 'הושלם'), ('CANCELED', 'בוטל')], db_index=True, default='DRAFT', max_length=20, verbose_name='סטטוס'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='עודכן'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='addition_cut',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='חיתוך / קיצור נוסף'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='הערה למוצר'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_hinge1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='גובה ציר 1 (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_hinge2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='גובה ציר 2 (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_hinge3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='גובה ציר 3 (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_hinge4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='גובה ציר 4 (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_hinge5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='גובה ציר 5 (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_lock_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='גובה מנעול מותאם (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='direction',
            field=models.CharField(blank=True, choices=[('LEFT', 'שמאל'), ('RIGHT', 'ימין')], max_length=10, null=True, verbose_name='כיוון פתיחה'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderitemsgroup', verbose_name='קבוצת פריטים'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='גובה (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='opening',
            field=models.CharField(blank=True, choices=[('LEFT', 'שמאל (L)'), ('RIGHT', 'ימין (R)')], max_length=10, null=True, verbose_name='צד פתיחה'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='מיקום התקנה (קומה / ציר / חדר)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wall',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='עובי קיר / פתח (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='רוחב (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='color_frames',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע משקופים'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='color_panels',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע פנלים (כנף)'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='front',
            field=models.ForeignKey(blank=True, help_text='אם ריק - יימשך מההזמנה', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.front', verbose_name='חזית / גימור'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='is_split_installation',
            field=models.BooleanField(default=False, help_text='True = משקוף וכנף בתאריכים שונים, False = בו זמנית', verbose_name='התקנה מפוצלת'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='orders.order', verbose_name='הזמנה'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_groups', to='catalog.productmodel', verbose_name='דגם מוצר'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='מספר פריטים זהים (דלתות) בקבוצה זו', verbose_name='כמות בקבוצה'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='series',
            field=models.ForeignKey(blank=True, help_text='אם ריק - יימשך מההזמנה', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.series', verbose_name='סדרה'),
        ),
    ]
