# Generated by Django 6.0.3 on 2026-08-05 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_orderitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='OrderChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='זמן שינוי')),
                ('field_name', models.CharField(max_length=100, verbose_name='שדה')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='ערך ישן')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='ערך חדש')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', to='orders.order', verbose_name='הזמנה')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'יומן שינויים',
                'verbose_name_plural': 'יומני שינויים',
                'ordering': ['-timestamp'],
            },
        ),
    ]
