# Generated by Django 6.0.3 on 2026-08-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_start_date_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_frames_to_paint',
            field=models.BooleanField(default=False, verbose_name='לצבוע משקופים?'),
        ),
        migrations.AddField(
            model_name='orderitemsgroup',
            name='frame_paint_option',
            field=models.CharField(choices=[('NO_PAINT', 'לא לצבוע'), ('MAIN_COLOR', 'גוון ראשי'), ('SPECIAL_COLOR', 'גוון מיוחד')], default='NO_PAINT', max_length=20, verbose_name='אופציית צביעת משקוף'),
        ),
        migrations.AddField(
            model_name='orderitemsgroup',
            name='panel_paint_option',
            field=models.CharField(choices=[('NO_PAINT', 'לא לצבוע'), ('MAIN_COLOR', 'גוון ראשי'), ('SPECIAL_COLOR', 'גוון מיוחד')], default='MAIN_COLOR', max_length=20, verbose_name='אופציית צביעת פנל'),
        ),
    ]
