# Generated by Django 6.0.3 on 2026-08-06 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_customizer_options_alter_front_options_and_more'),
        ('orders', '0007_order_is_frames_to_paint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemsGroupCustomizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par1', models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 1')),
                ('par2', models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 2')),
                ('par3', models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 3')),
                ('par4', models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 4')),
                ('customizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.customizer', verbose_name='קסטומייזר')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizers', to='orders.orderitemsgroup', verbose_name='קבוצת פריטים')),
            ],
            options={
                'verbose_name': 'קסטומייזר לקבוצה',
                'verbose_name_plural': 'קסטומייזרים לקבוצה',
            },
        ),
    ]
