# Generated by Django 6.0.3 on 2026-08-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sketch',
            field=models.FileField(blank=True, help_text='ניתן להעלות PDF, JPEG, PNG וכדומה', null=True, upload_to='order_sketches/%Y/%m/', verbose_name='שרטוט ידני / קובץ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderitemsgroup', verbose_name='קבוצת מוצרים'),
        ),
    ]
