# Generated by Django 6.0.3 on 2026-08-06 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_sketch_alter_orderitem_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='mark',
        ),
    ]
