# Generated by Django 6.0.3 on 2026-08-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderitem_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='mark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='סימון'),
        ),
    ]
