# Generated by Django 6.0.3 on 2026-08-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='custom_hinge1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='גובה ציר 1 (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_hinge2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='גובה ציר 2 (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_hinge3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='גובה ציר 3 (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_hinge4',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='גובה ציר 4 (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_hinge5',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='גובה ציר 5 (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_lock_height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='גובה מנעול מותאם (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='direction',
            field=models.CharField(blank=True, choices=[('IN', 'פנימה'), ('OUT', 'החוצה')], max_length=10, null=True, verbose_name='כיוון פתיחה'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='גובה (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wall',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='עובי קיר / פתח (מ""מ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='רוחב (מ""מ)'),
        ),
    ]
