# Generated by Django 6.0.3 on 2026-08-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderitem_custom_hinge1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='mark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='#'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='opening',
            field=models.CharField(blank=True, choices=[('LEFT', 'L'), ('RIGHT', 'R')], max_length=10, null=True, verbose_name='צד פתיחה'),
        ),
    ]
