# Generated by Django 6.0.3 on 2026-08-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderitem_mark_alter_orderitem_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='addition_cut',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='חיתוך / קיצור נוסף'),
        ),
    ]
