# Generated by Django 6.0.3 on 2026-08-09 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_handle'),
        ('orders', '0015_alter_orderitem_addition_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='handle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.handle', verbose_name='ידית'),
        ),
    ]
