# Generated by Django 6.0.3 on 2026-08-09 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phase1_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך סיום שלב א'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'טיוטה'), ('MEASUREMENT', 'ממתין למדידה'), ('IN_PRODUCTION', 'בייצור'), ('PHASE1_PRODUCTION', 'ייצור שלב א (משקופים)'), ('PHASE1_READY', 'שלב א מוכן (ממתין להמשך)'), ('READY', 'מוכן למשלוח'), ('COMPLETED', 'הושלם'), ('CANCELED', 'בוטל')], db_index=True, default='DRAFT', max_length=20, verbose_name='סטטוס'),
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PHASE1', 'שלב א (משקופים)'), ('PHASE2', 'שלב ב (כנפיים והשאר)')], default='PHASE1', max_length=20, verbose_name='שלב')),
                ('status', models.CharField(choices=[('DRAFT', 'טיוטה'), ('MEASUREMENT', 'ממתין למדידה'), ('IN_PRODUCTION', 'בייצור'), ('PHASE1_PRODUCTION', 'ייצור שלב א (משקופים)'), ('PHASE1_READY', 'שלב א מוכן (ממתין להמשך)'), ('READY', 'מוכן למשלוח'), ('COMPLETED', 'הושלם'), ('CANCELED', 'בוטל')], default='IN_PRODUCTION', max_length=20, verbose_name='סטטוס')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='תאריך סיום צפוי')),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='תאריך סיום בפועל')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.orderitemsgroup', verbose_name='קבוצה')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.order', verbose_name='הזמנה')),
            ],
            options={
                'verbose_name': 'תת-הזמנה (שלב)',
                'verbose_name_plural': 'תת-הזמנות (שלבים)',
                'db_table': 'sub_orders',
            },
        ),
    ]
