# Generated by Django 6.0.3 on 2026-08-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_phase1_completion_date_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='direction',
            field=models.CharField(blank=True, choices=[('LEFT', 'L'), ('RIGHT', 'R')], max_length=10, null=True, verbose_name='כיוון פתיחה'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='opening',
            field=models.CharField(blank=True, choices=[('IN', 'פנימה'), ('OUT', 'החוצה')], max_length=10, null=True, verbose_name='צד פתיחה'),
        ),
    ]
