# Generated by Django 6.0.3 on 2026-08-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_orderitem_direction_alter_orderitem_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='direction',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('R', 'R')], max_length=10, null=True, verbose_name='כיוון פתיחה'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='opening',
            field=models.CharField(blank=True, choices=[('IN', 'פנימה'), ('OUT', 'החוצה')], default='IN', max_length=10, null=True, verbose_name='צד פתיחה'),
        ),
    ]
