# Generated by Django 6.0.3 on 2026-08-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orderitem_direction_alter_orderitem_opening'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='painting_date',
            new_name='painting_completion_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='painting_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך סיום צבע'),
        ),
    ]
