# Generated by Django 6.0.3 on 2026-08-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_remove_order_painting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='opening',
            field=models.CharField(blank=True, choices=[('IN', 'פנימה'), ('OUT', 'החוצה')], max_length=10, null=True, verbose_name='צד פתיחה'),
        ),
    ]
