# Generated by Django 6.0.3 on 2026-08-18 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productfamily_default_value_for_frame'),
        ('orders', '0021_alter_orderitem_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basic_color_frames',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.framecolor', verbose_name='צבע משקוף בסיסי'),
        ),
        migrations.AddField(
            model_name='orderitemsgroup',
            name='basic_color_frames',
            field=models.ForeignKey(blank=True, help_text='אם ריק - יימשך מההזמנה', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.framecolor', verbose_name='צבע משקוף בסיסי'),
        ),
    ]
