# Generated by Django 6.0.3 on 2026-08-23 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_framecolor_unique_together_and_more'),
        ('orders', '0022_order_basic_color_frames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basic_color_frames',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.color', verbose_name='צבע משקוף בסיסי'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='basic_color_frames',
            field=models.ForeignKey(blank=True, help_text='אם ריק - יימשך מההזמנה', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.color', verbose_name='צבע משקוף בסיסי'),
        ),
    ]
