# Generated by Django 6.0.3 on 2026-08-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_material_color'),
        ('orders', '0023_alter_order_basic_color_frames_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basic_color_frames',
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='basic_color_frames',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.material', verbose_name='צבע משקוף בסיסי'),
        ),
    ]
