# Generated by Django 6.0.3 on 2026-08-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_order_basic_color_frames_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubOrder',
        ),
    ]
