# Generated by Django 6.0.3 on 2026-08-31 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_customizer_strategy'),
        ('orders', '0025_delete_suborder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='שם מזהה למפרט השמור (למשל: דלתות קומה טיפוסית)', max_length=255, verbose_name='שם המפרט')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
                ('panel_paint_option', models.CharField(choices=[('NO_PAINT', 'לא לצבוע'), ('MAIN_COLOR', 'גוון ראשי'), ('SPECIAL_COLOR', 'גוון מיוחד')], default='MAIN_COLOR', max_length=20, verbose_name='אופציית צביעת פנל')),
                ('color_panels', models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע פנלים (כנף)')),
                ('frame_paint_option', models.CharField(choices=[('NO_PAINT', 'לא לצבוע'), ('MAIN_COLOR', 'גוון ראשי'), ('SPECIAL_COLOR', 'גוון מיוחד')], default='NO_PAINT', max_length=20, verbose_name='אופציית צביעת משקוף')),
                ('color_frames', models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע משקופים')),
                ('is_split_installation', models.BooleanField(default=False, verbose_name='התקנה מפוצלת')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות דלתות ברירת מחדל')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר במערכת')),
                ('basic_color_frames', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.material', verbose_name='צבע משקוף בסיסי')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='נוצר ע"י')),
                ('front', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.front', verbose_name='חזית / גימור')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_specifications', to='catalog.productmodel', verbose_name='דגם מוצר')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.series', verbose_name='סדרה')),
            ],
            options={
                'verbose_name': 'מפרט קבוצה שמור',
                'verbose_name_plural': 'מפרטי קבוצות שמורים',
                'db_table': 'group_specifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupSpecificationCustomizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par1', models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 1')),
                ('par2', models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 2')),
                ('par3', models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 3')),
                ('par4', models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 4')),
                ('customizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.customizer', verbose_name='קסטומייזר')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizers', to='orders.groupspecification', verbose_name='מפרט')),
            ],
            options={
                'verbose_name': 'קסטומייזר למפרט',
                'verbose_name_plural': 'קסטומייזרים למפרט',
                'db_table': 'group_specification_customizers',
            },
        ),
    ]
