# Generated by Django 6.0.3 on 2026-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_groupspecification_groupspecificationcustomizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'חדש'), ('IN_PRODUCTION', 'בייצור'), ('PHASE1_PRODUCTION', 'ייצור שלב א (משקופים)'), ('PHASE1_READY', 'שלב א מוכן (ממתין להמשך)'), ('READY', 'מוכן למשלוח'), ('COMPLETED', 'הושלם'), ('CANCELED', 'בוטל')], db_index=True, default='NEW', max_length=20, verbose_name='סטטוס'),
        ),
    ]
