# Generated by Django 6.0.3 on 2026-09-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phase1_spec_cache',
            field=models.JSONField(blank=True, null=True, verbose_name='מטמון מפרט שלב א'),
        ),
        migrations.AddField(
            model_name='order',
            name='phase1_validated',
            field=models.BooleanField(default=False, verbose_name="שלב א' מאושר"),
        ),
        migrations.AddField(
            model_name='order',
            name='phase2_spec_cache',
            field=models.JSONField(blank=True, null=True, verbose_name='מטמון מפרט שלב ב'),
        ),
        migrations.AddField(
            model_name='order',
            name='phase2_validated',
            field=models.BooleanField(default=False, verbose_name="שלב ב' מאושר"),
        ),
    ]
