# Generated by Django 6.0.3 on 2026-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_order_phase1_spec_cache_order_phase1_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupspecificationcustomizer',
            name='par5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='5'),
        ),
    ]
