# Generated by Django 6.0.3 on 2026-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_groupspecificationcustomizer_par5'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemsgroupcustomizer',
            name='par5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 5'),
        ),
    ]
