# Generated by Django 6.0.3 on 2026-09-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_orderitemsgroupcustomizer_par5'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemsgroup',
            name='production_state',
            field=models.CharField(choices=[('WAITING', 'ממתין'), ('IN_PRODUCTION', 'בייצור'), ('COMPLETED', 'הושלם')], db_index=True, default='WAITING', max_length=20, verbose_name='סטטוס ייצור של הקבוצה'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'חדש'), ('IN_PRODUCTION', 'בייצור'), ('PHASE1_PRODUCTION', 'ייצור שלב א (משקופים)'), ('PHASE1_READY', 'שלב א מוכן (ממתין להמשך)'), ('PHASE2_PRODUCTION', 'ייצור שלב ב'), ('COMPLETION_PRODUCTION', 'ייצור השלמות'), ('READY', 'מוכן למשלוח'), ('COMPLETED', 'הושלם'), ('CANCELED', 'בוטל')], db_index=True, default='NEW', max_length=30, verbose_name='סטטוס'),
        ),
    ]
