# Generated by Django 6.0.3 on 2026-09-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_orderitemsgroup_production_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='production_state',
            field=models.CharField(choices=[('NEW', 'חדש'), ('WAITING', 'ממתין'), ('IN_PRODUCTION', 'בייצור'), ('COMPLETED', 'הושלם'), ('CANCELED', 'בוטל')], db_index=True, default='NEW', max_length=20, verbose_name='סטטוס ייצור של הקבוצה'),
        ),
    ]
