# Generated by Django 6.0.3 on 2026-09-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_orderitemsgroup_production_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='addition_cut',
            new_name='bottom_correction',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'חדש'), ('IN_PRODUCTION', 'בייצור'), ('PHASE1_PRODUCTION', 'ייצור שלב א (משקופים)'), ('PHASE1_READY', 'שלב א מוכן (ממתין להמשך)'), ('PHASE2_PRODUCTION', 'ייצור שלב ב'), ('COMPLETION_PRODUCTION', 'ייצור השלמות'), ('PARTIALLY_READY', 'מוכן חלקית (ממתין להשלמות)'), ('COMPLETED', 'ההזמנה מוכנה'), ('CANCELED', 'בוטל')], db_index=True, default='NEW', max_length=30, verbose_name='סטטוס'),
        ),
    ]
