# Generated by Django 6.0.3 on 2026-09-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_rename_addition_cut_orderitem_bottom_correction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='bottom_correction',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='חיתוך / קיצור נוסף'),
        ),
    ]
