# Generated by Django 6.0.3 on 2026-09-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_alter_orderitem_bottom_correction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='color_panels',
        ),
        migrations.RemoveField(
            model_name='orderitemsgroup',
            name='color_panels',
        ),
        migrations.AddField(
            model_name='order',
            name='color_panel_inside',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע כנף בפנים '),
        ),
        migrations.AddField(
            model_name='order',
            name='color_panel_outside',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע כנף בחוץ '),
        ),
        migrations.AddField(
            model_name='order',
            name='is_door_inside_different_color',
            field=models.BooleanField(default=False, verbose_name='צד שני צבע אחר'),
        ),
        migrations.AddField(
            model_name='orderitemsgroup',
            name='color_panel_inside',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע כנף בפנים '),
        ),
        migrations.AddField(
            model_name='orderitemsgroup',
            name='color_panel_outside',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע כנף בחוץ '),
        ),
        migrations.AddField(
            model_name='orderitemsgroup',
            name='is_door_inside_different_color',
            field=models.BooleanField(default=False, verbose_name='צד שני צבע אחר'),
        ),
    ]
