# Generated by Django 6.0.3 on 2026-09-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_remove_order_color_panels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='color_frames',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע משקוף (מיוחד)'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='color_panel_inside',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע כנף פנים (מיוחד)'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='color_panel_outside',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='צבע כנף חוץ (מיוחד)'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='is_door_inside_different_color',
            field=models.BooleanField(default=False, verbose_name='צדדים שונים (חוץ/פנים)'),
        ),
        migrations.AlterField(
            model_name='orderitemsgroup',
            name='panel_paint_option',
            field=models.CharField(choices=[('NO_PAINT', 'לא לצבוע'), ('MAIN_COLOR', 'גוון ראשי'), ('SPECIAL_COLOR', 'גוון מיוחד')], default='MAIN_COLOR', max_length=20, verbose_name='אופציית צביעת כנף'),
        ),
    ]
