# Generated by Django 6.0.3 on 2026-10-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_alter_orderitemsgroup_color_frames_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latest_batch',
            field=models.PositiveSmallIntegerField(default=0, help_text='Tracks the latest released production batch number'),
        ),
        migrations.AddField(
            model_name='orderitemsgroup',
            name='batch_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order release wave (1 for initial order, 2+ for subsequent additions)', null=True),
        ),
    ]
