# Generated by Django 6.0.3 on 2026-10-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_order_latest_batch_orderitemsgroup_batch_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phase1_completion_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phase1_validated',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phase2_validated',
        ),
        migrations.AddField(
            model_name='order',
            name='production_start_date',
            field=models.DateField(blank=True, help_text='Дата первого запуска заказа в производство', null=True, verbose_name='ירידה לייצור'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'פעיל'), ('CANCELED', 'בוטל')], db_index=True, default='ACTIVE', max_length=20, verbose_name='סטטוס פריט'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Плановая дата окончания производства в цеху', null=True, verbose_name='סיום ייצור'),
        ),
        migrations.AlterField(
            model_name='order',
            name='painting_completion_date',
            field=models.DateField(blank=True, help_text='Плановая дата окончания покраски', null=True, verbose_name='סיום צבע'),
        ),
    ]
