# Generated by Django 6.0.3 on 2026-08-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_alter_customizer_options_alter_front_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTechnicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnc_program_name', models.CharField(blank=True, help_text='Например: door_v1_standard.prg', max_length=255, verbose_name='Имя программы ЧПУ')),
                ('technical_notes', models.TextField(blank=True, help_text='Инструкции для работников цеха', verbose_name='Технические примечания')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_data', to='catalog.productmodel', verbose_name='Модель продукции')),
            ],
            options={
                'verbose_name': 'Технические данные изделия',
                'verbose_name_plural': 'Технические данные изделий',
            },
        ),
    ]
