# Generated by Django 6.0.3 on 2026-08-06 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_customizer_options_alter_front_options_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttechnicaldata',
            options={'verbose_name': 'נתונים טכניים של המוצר', 'verbose_name_plural': 'נתונים טכניים של מוצרים'},
        ),
        migrations.AlterField(
            model_name='producttechnicaldata',
            name='cnc_program_name',
            field=models.CharField(blank=True, help_text='למשל: door_v1_standard.prg', max_length=255, verbose_name='שם תוכנית CNC'),
        ),
        migrations.AlterField(
            model_name='producttechnicaldata',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_data', to='catalog.productmodel', verbose_name='דגם מוצר'),
        ),
        migrations.AlterField(
            model_name='producttechnicaldata',
            name='technical_notes',
            field=models.TextField(blank=True, help_text='הוראות לעובדי הייצור', verbose_name='הערות טכניות'),
        ),
    ]
