# Generated by Django 6.0.3 on 2026-08-09 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_hardware_delete_productmaterial'),
        ('production', '0002_alter_producttechnicaldata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_formula', models.CharField(default='1', help_text='נוסחה לחישוב כמות (למשל: H * W / 1000000)', max_length=255, verbose_name='נוסחת כמות')),
                ('inclusion_condition', models.CharField(blank=True, help_text='תנאי להכללת הפריט ב-BOM (למשל: has_frame == True)', max_length=255, verbose_name='תנאי הכללה')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='הערה')),
                ('child_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contained_in_bom', to='catalog.productmodel', verbose_name='מוצר בן (BOM מוטמע)')),
                ('hardware', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_bom', to='catalog.hardware', verbose_name='פרזול')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_bom', to='catalog.material', verbose_name='חומר')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='catalog.productmodel', verbose_name='מוצר אב')),
            ],
            options={
                'verbose_name': 'פריט עץ מוצר (BOM)',
                'verbose_name_plural': 'פריטי עץ מוצר (BOM)',
            },
        ),
    ]
