# Generated by Django 6.0.3 on 2026-08-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_bomitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='tag',
            field=models.CharField(blank=True, help_text='תג לזיהוי פריט (למשл: Lock, hinge)', max_length=50, verbose_name='תג'),
        ),
    ]
