# Generated by Django 6.0.3 on 2026-08-12 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_hardware_delete_productmaterial'),
        ('production', '0004_bomitem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covering_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת כיסוי')),
                ('base_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת בסיס')),
                ('filling_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת מילוי')),
                ('casing_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת הלבשה')),
                ('frame_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת משקוף')),
                ('profile1_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת פרופיל 1')),
                ('profile2_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת פרופיל 2')),
                ('profile3_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת פרופיל 3')),
                ('other1_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת אחר 1')),
                ('other2_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת אחר 2')),
                ('other3_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת אחר 3')),
                ('other4_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת אחר 4')),
                ('other5_consumption', models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת אחר 5')),
                ('additional', models.ManyToManyField(blank=True, related_name='+', to='catalog.hardware', verbose_name='תוספות (Additional)')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='בסיס (Base)')),
                ('casing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='הלבשה (Casing)')),
                ('covering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='כיסוי (Covering)')),
                ('filling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='מילוי (Filling)')),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='משקוף (Frame)')),
                ('hinges', models.ManyToManyField(blank=True, related_name='+', to='catalog.hardware', verbose_name='צירים (Hinges)')),
                ('lock', models.ManyToManyField(blank=True, related_name='+', to='catalog.hardware', verbose_name='מנעול (Lock)')),
                ('nested_boms', models.ManyToManyField(blank=True, related_name='parent_boms', to='production.bom', verbose_name='BOM מוטמע')),
                ('other1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='אחר 1')),
                ('other2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='אחר 2')),
                ('other3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='אחר 3')),
                ('other4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='אחר 4')),
                ('other5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='אחר 5')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='catalog.productmodel', verbose_name='דגם מוצר')),
                ('profile1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='פרופיל 1')),
                ('profile2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='פרופיל 2')),
                ('profile3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='פרופיל 3')),
            ],
            options={
                'verbose_name': 'עץ מוצר (BOM)',
                'verbose_name_plural': 'עצי מוצר (BOM)',
            },
        ),
        migrations.DeleteModel(
            name='BOMItem',
        ),
    ]
