# Generated by Django 6.0.3 on 2026-08-12 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_hardware_delete_productmaterial'),
        ('production', '0005_bom_delete_bomitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HingeStandardHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_height', models.DecimalField(decimal_places=2, help_text='מינימום גובה דלת בטווח', max_digits=7, verbose_name='גובה מינימלי')),
                ('max_height', models.DecimalField(decimal_places=2, help_text='מקסימום גובה דלת בטווח', max_digits=7, verbose_name='גובה מקסימלי')),
                ('value1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='גובה ציר 1')),
                ('value2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='גובה ציר 2')),
                ('value3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='גובה ציר 3')),
                ('value4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='גובה ציר 4')),
                ('value5', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='גובה ציר 5')),
                ('hinge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.hardware', verbose_name='ציר (Hinge)')),
                ('product_families', models.ManyToManyField(related_name='hinge_heights', to='catalog.productfamily', verbose_name='משפחות מוצרים')),
            ],
            options={
                'verbose_name': 'גובה צירים סטנדרטי',
                'verbose_name_plural': 'גבהי צירים סטנדרטיים',
            },
        ),
        migrations.CreateModel(
            name='LockStandardHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_door_height', models.DecimalField(decimal_places=2, help_text='גובה דלת לייחוס (למשל 2000 מ"מ)', max_digits=7, verbose_name='גובה דלת בסיסי')),
                ('base_lock_height', models.DecimalField(decimal_places=2, help_text='מיקום המנעול בגובה הבסיסי', max_digits=7, verbose_name='גובה מנעול בסיסי')),
                ('step', models.DecimalField(decimal_places=2, default=0, help_text='שינוי בגובה המנעול לכל יחידת גובה דלת', max_digits=7, verbose_name='צעד (Step)')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.hardware', verbose_name='מנעול (Lock)')),
                ('product_families', models.ManyToManyField(related_name='lock_heights', to='catalog.productfamily', verbose_name='משפחות מוצרים')),
            ],
            options={
                'verbose_name': 'גובה מנעול סטנדרטי',
                'verbose_name_plural': 'גבהי מנעול סטנדרטיים',
            },
        ),
    ]
