# Generated by Django 6.0.3 on 2026-09-02 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_customizer_strategy'),
        ('production', '0006_hingestandardheight_lockstandardheight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='שם התחנה')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='קוד תחנה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('priority', models.IntegerField(default=100, verbose_name='עדיפות (סדר בייצור)')),
                ('active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('product_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_stations', to='catalog.productfamily', verbose_name='משפחת מוצרים')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_stations', to='catalog.productmodel', verbose_name='דגם מוצר')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_stations', to='catalog.producttype', verbose_name='סוג מוצר')),
            ],
            options={
                'verbose_name': 'תחנת ייצור',
                'verbose_name_plural': 'תחנות ייצור',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
