# Generated by Django 6.0.3 on 2026-09-02 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_customizer_strategy'),
        ('production', '0007_productionstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstation',
            name='product_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_stations_direct', to='catalog.productfamily', verbose_name='משפחת מוצרים'),
        ),
        migrations.AlterField(
            model_name='productionstation',
            name='product_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_stations_direct', to='catalog.productmodel', verbose_name='דגם מוצר'),
        ),
        migrations.AlterField(
            model_name='productionstation',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_stations_direct', to='catalog.producttype', verbose_name='סוג מוצר'),
        ),
    ]
