# Generated by Django 6.0.3 on 2026-09-02 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_customizer_strategy'),
        ('production', '0008_alter_productionstation_product_family_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionstation',
            options={'ordering': ['name'], 'verbose_name': 'תחנת ייצור', 'verbose_name_plural': 'תחנות ייצור'},
        ),
        migrations.RemoveField(
            model_name='productionstation',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='productionstation',
            name='product_family',
        ),
        migrations.RemoveField(
            model_name='productionstation',
            name='product_model',
        ),
        migrations.RemoveField(
            model_name='productionstation',
            name='product_type',
        ),
        migrations.CreateModel(
            name='ProductionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='שם המסלול')),
                ('active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('product_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_routes', to='catalog.productfamily', verbose_name='משפחת מוצרים')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_routes', to='catalog.productmodel', verbose_name='דגם מוצר')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_routes', to='catalog.producttype', verbose_name='סוג מוצר')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_routes', to='catalog.series', verbose_name='סדרה')),
            ],
            options={
                'verbose_name': 'מסלול ייצור',
                'verbose_name_plural': 'מסלולי ייצור',
            },
        ),
        migrations.CreateModel(
            name='ProductionRouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=10, verbose_name='סדר')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.productionroute', verbose_name='מסלול')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_steps', to='production.productionstation', verbose_name='תחנה')),
            ],
            options={
                'verbose_name': 'שלב במסלול',
                'verbose_name_plural': 'שלבים במסלול',
                'ordering': ['order'],
            },
        ),
    ]
