# Generated by Django 6.0.3 on 2026-09-02 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_customizer_strategy'),
        ('production', '0009_alter_productionstation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstation',
            name='has_specification',
            field=models.BooleanField(default=True, help_text='האם להציג כפתור להפקת דו"ח עבור תחנה זו', verbose_name='יש מפרט/כפתור'),
        ),
        migrations.AddField(
            model_name='productionstation',
            name='hint',
            field=models.CharField(blank=True, help_text='יופיע כ-tooltip', max_length=255, verbose_name='רמז/תיאור קצר'),
        ),
        migrations.AddField(
            model_name='productionstation',
            name='label',
            field=models.CharField(blank=True, help_text='הטקסט שיופיע על הכפתור', max_length=100, verbose_name='תווית לכפתור'),
        ),
        migrations.AddField(
            model_name='productionstation',
            name='template_name',
            field=models.CharField(blank=True, help_text='נתיב לקובץ ה-html של הדו"ח', max_length=255, verbose_name='שם תבנית HTML'),
        ),
        migrations.AlterField(
            model_name='productionstation',
            name='description',
            field=models.TextField(blank=True, verbose_name='תיאור מפורט'),
        ),
        migrations.CreateModel(
            name='CustomizerProductionStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_stations', to='catalog.customizer', verbose_name='קסטומייזר')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizer_links', to='production.productionstation', verbose_name='תחנת ייצור')),
            ],
            options={
                'verbose_name': 'תחנה לקסטומייזר',
                'verbose_name_plural': 'תחנות לקסטומייזרים',
                'unique_together': {('customizer', 'station')},
            },
        ),
    ]
