# Generated by Django 6.0.3 on 2026-09-02 08:30

from django.db import migrations


def seed_stations(apps, schema_editor):
    ProductionStation = apps.get_model('production', 'ProductionStation')
    
    stations = [
        {
            'name': 'משקופים',
            'code': 'FRAMES',
            'label': 'משקופים',
            'hint': 'הפקת דו"ח ייצור משקופים',
            'template_name': 'production/alum_frames_report.html',
            'has_specification': True
        },
        {
            'name': 'פרס',
            'code': 'PRESS',
            'label': 'פרס',
            'hint': 'דו"ח עמדת פרס',
            'template_name': 'production/alum_frames_report.html', # Placeholder
            'has_specification': True
        },
        {
            'name': 'זיגוג',
            'code': 'GLAZING',
            'label': 'זיגוג',
            'hint': 'דו"ח עמדת זיגוג',
            'template_name': 'production/alum_frames_report.html', # Placeholder
            'has_specification': True
        },
        {
            'name': 'נגרות',
            'code': 'CARPENTRY',
            'label': 'נגרות',
            'hint': 'דו"ח עמדת נגרות',
            'template_name': 'production/alum_frames_report.html', # Placeholder
            'has_specification': True
        },
    ]
    
    for s_data in stations:
        ProductionStation.objects.get_or_create(code=s_data['code'], defaults=s_data)

class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_productionstation_has_specification_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_stations),
    ]
