# Generated by Django 6.0.3 on 2026-09-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_seed_production_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstation',
            name='is_phase1',
            field=models.BooleanField(default=False, help_text='האם תחנה זו שייכת לשלב א (ייצור מקדים/משקופים)', verbose_name='שלב א'),
        ),
    ]
