# Generated by Django 6.0.3 on 2026-09-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_remove_customizer_hardware_list_and_more'),
        ('production', '0012_productionstation_is_phase1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hingestandardheight',
            name='hinge',
        ),
        migrations.RemoveField(
            model_name='lockstandardheight',
            name='lock',
        ),
        migrations.AddField(
            model_name='hingestandardheight',
            name='hinges',
            field=models.ManyToManyField(related_name='hinge_heights', to='catalog.hardware', verbose_name='צירים (Hinges)'),
        ),
        migrations.AddField(
            model_name='lockstandardheight',
            name='locks',
            field=models.ManyToManyField(related_name='lock_heights', to='catalog.hardware', verbose_name='מנעולים (Locks)'),
        ),
    ]
