# Generated by Django 6.0.3 on 2026-09-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_remove_hingestandardheight_hinge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hingestandardheight',
            name='hinge_count',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False, verbose_name='כמות צירים'),
        ),
    ]
