# Generated by Django 6.0.3 on 2026-09-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_profilegeometry_customizer_profile_geometry_and_more'),
        ('production', '0014_hingestandardheight_hinge_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='frame_geometry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.profilegeometry', verbose_name='גיאומטריית משקוף (Frame Geometry)'),
        ),
    ]
