# Generated by Django 6.0.3 on 2026-09-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_bom_frame_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='frame_geometry',
        ),
    ]
