# Generated by Django 6.0.3 on 2026-09-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_remove_bom_frame_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='nested_boms',
        ),
    ]
