# Generated by Django 6.0.3 on 2026-09-09 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_remove_customizer_requires_door_and_more'),
        ('production', '0017_remove_bom_nested_boms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='hinges',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='lock',
        ),
        migrations.AddField(
            model_name='bom',
            name='hinges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.hardware', verbose_name='צירים (Hinges)'),
        ),
        migrations.AddField(
            model_name='bom',
            name='lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.hardware', verbose_name='מנעול (Lock)'),
        ),
    ]
