# Generated by Django 6.0.3 on 2026-09-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_remove_bom_hinges_remove_bom_lock_bom_hinges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='cut_coefficients',
            field=models.JSONField(blank=True, default=dict, help_text='מילון מקדמי חיתוך חלקים במילימטרים (למשל {"transom_delta": 45})', verbose_name='מקדמי חיתוך חלקים'),
        ),
    ]
