# Generated by Django 6.0.3 on 2026-09-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_customizer_is_required_customizer_par1_required_and_more'),
        ('production', '0019_bom_cut_coefficients'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='required_customizers',
            field=models.ManyToManyField(blank=True, related_name='required_for_boms', to='catalog.customizer', verbose_name='קסטומייזרים חובה'),
        ),
    ]
