# Generated by Django 6.0.3 on 2026-09-20 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_orderitemsgroup_production_state_alter_order_status'),
        ('production', '0020_bom_required_customizers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSpecificationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('PHASE1', 'שלב א (משקופים)'), ('PHASE2', 'שלב ב (דלתות)'), ('PHASE2_COMPLETION', 'השלמות שלב ב')], default='PHASE1', max_length=30, verbose_name='סוג סנאפשוט')),
                ('spec_data', models.JSONField(verbose_name='נתוני מפרט (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='זמן יצירה')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_snapshots', to='orders.order', verbose_name='הזמנה')),
            ],
            options={
                'verbose_name': 'סנאפשוט מפרט הזמנה',
                'verbose_name_plural': 'סנאפשוטים של מפרטי הזמנות',
                'ordering': ['-created_at'],
            },
        ),
    ]
