# Generated by Django 6.0.3 on 2026-09-27 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_alter_orderitem_bottom_correction'),
        ('production', '0021_orderspecificationsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=64)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('item_mark', models.CharField(max_length=32)),
                ('total_items', models.PositiveIntegerField(default=1)),
                ('label_type', models.IntegerField(choices=[(0, 'Черновая обгонка (до вкладного канта)'), (1, 'Стандартная обгонка'), (2, 'Фурнитура и замки')], default=1)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('thickness', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, default='', max_length=32)),
                ('opening', models.CharField(blank=True, default='', max_length=32)),
                ('edge_type', models.CharField(blank=True, default='', max_length=64)),
                ('is_paint', models.BooleanField(default=False)),
                ('lock_name', models.CharField(blank=True, default='', max_length=128)),
                ('lock_height', models.FloatField(blank=True, null=True)),
                ('hinge_name', models.CharField(blank=True, default='', max_length=128)),
                ('hinge_1', models.FloatField(blank=True, null=True)),
                ('hinge_2', models.FloatField(blank=True, null=True)),
                ('hinge_3', models.FloatField(blank=True, null=True)),
                ('hinge_4', models.FloatField(blank=True, null=True)),
                ('hinge_5', models.FloatField(blank=True, null=True)),
                ('addons_summary', models.TextField(blank=True, default='')),
                ('icon_filename', models.CharField(blank=True, default='', max_length=128)),
                ('comment', models.TextField(blank=True, default='')),
                ('target_machine', models.CharField(choices=[('ESSEPIGI', 'Essepigi'), ('ACCORD_STD', 'Accord (Библиотека)'), ('ACCORD_CUSTOM', 'Accord (Ручной проект)')], default='ACCORD_STD', max_length=32)),
                ('qr_payload', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_labels', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='orders.orderitem')),
            ],
            options={
                'ordering': ['item_mark', 'label_type'],
                'indexes': [models.Index(fields=['order_number', 'print_count'], name='production__order_n_1db884_idx'), models.Index(fields=['order', 'label_type'], name='production__order_i_7c5659_idx')],
            },
        ),
    ]
