# Generated by Django 6.0.3 on 2026-10-04 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_productmodel_allowed_direction'),
        ('production', '0022_doorlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='panel_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material', verbose_name='מסגרת עץ'),
        ),
        migrations.AddField(
            model_name='bom',
            name='panel_frame_consumption',
            field=models.CharField(blank=True, default='1', max_length=255, verbose_name='צריכת מסגרת עץ'),
        ),
    ]
