# Generated by Django 6.0.3 on 2026-10-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_productmodel_allowed_direction'),
        ('production', '0023_bom_panel_frame_bom_panel_frame_consumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzlePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название пресета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('blocks_config', models.JSONField(blank=True, default=list, verbose_name='Конфигурация блоков')),
            ],
            options={
                'verbose_name': 'Пресет узла (Пиктограмма)',
                'verbose_name_plural': 'Пресеты узлов (Пиктограммы)',
            },
        ),
        migrations.CreateModel(
            name='SvgPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Латинский ключ для SVG ID (например: foam, tubular, honeycomb)', max_length=50, unique=True, verbose_name='Идентификатор (slug)')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('width', models.PositiveIntegerField(default=20, verbose_name='Ширина тайла (px)')),
                ('height', models.PositiveIntegerField(default=20, verbose_name='Высота тайла (px)')),
                ('svg_content', models.TextField(help_text='Теги rect, circle, path, line без обрамляющего тега <pattern>', verbose_name='Внутренний SVG-контент')),
            ],
            options={
                'verbose_name': 'SVG Паттерн',
                'verbose_name_plural': 'SVG Паттерны',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CustomizerPuzzleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_action', models.CharField(choices=[('ADD', 'הוספה (Add blocks)'), ('REPLACE', 'החלפה (Replace slot)'), ('REMOVE', 'הסרה (Clear slot)')], default='ADD', max_length=10, verbose_name='פעולה על סלוט')),
                ('target_slot', models.CharField(blank=True, help_text='FILLING, FRAME, BASE, COVERING (עבור החלפה או הסרה)', max_length=30, null=True, verbose_name='סלוט יעד')),
                ('customizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_mapping', to='catalog.customizer', verbose_name='קסטומייזר')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizer_mappings', to='production.puzzlepreset', verbose_name='פיקטוגרמה')),
            ],
            options={
                'verbose_name': 'מיפוי פיקטוגרמה לקסטומייזר',
                'verbose_name_plural': 'מיפוי פיקטוגרמות לקסטומייזרים',
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='base_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.puzzlepreset', verbose_name='פיקטוגרמה: בסיס'),
        ),
        migrations.AddField(
            model_name='bom',
            name='covering_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.puzzlepreset', verbose_name='פיקטוגרמה: כיסוי'),
        ),
        migrations.AddField(
            model_name='bom',
            name='filling_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.puzzlepreset', verbose_name='פיקטוגרמה: מילוי'),
        ),
        migrations.AddField(
            model_name='bom',
            name='panel_frame_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.puzzlepreset', verbose_name='פיקטוגרמה: מסגרת עץ'),
        ),
        migrations.CreateModel(
            name='PuzzleBlockPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Например: pine_timber, green_hdf, tubular_core', max_length=50, unique=True, verbose_name='Код прототипа')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('fill_type', models.CharField(choices=[('SOLID', 'Сплошной цвет'), ('PATTERN', 'SVG Паттерн')], default='SOLID', max_length=10, verbose_name='Тип заполнения')),
                ('fill_color', models.CharField(default='#fab005', max_length=30, verbose_name='Цвет заливки (HEX)')),
                ('border_color', models.CharField(default='#000000', max_length=30, verbose_name='Цвет границы')),
                ('border_width', models.FloatField(default=1.0, verbose_name='Толщина границы')),
                ('border_dasharray', models.CharField(blank=True, default='', max_length=30, verbose_name='Пунктир')),
                ('opacity', models.FloatField(default=1.0, verbose_name='Непрозрачность (0.0 - 1.0)')),
                ('default_text_color', models.CharField(default='#000000', max_length=30, verbose_name='Цвет текста')),
                ('default_font_size', models.PositiveSmallIntegerField(default=11, verbose_name='Размер шрифта')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_prototypes', to='production.svgpattern', verbose_name='Паттерн')),
            ],
            options={
                'verbose_name': 'Прототип блока пазла',
                'verbose_name_plural': 'Прототипы блоков пазла',
            },
        ),
    ]
