# Generated by Django 6.0.3 on 2026-07-30 19:42

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=apps.accounts.models.UserRole.choices, default=apps.accounts.models.UserRole['USER'], max_length=20, verbose_name='User Role'),
        ),
    ]
