# Generated by Django 6.0.3 on 2026-08-05 08:45

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'משתמש', 'verbose_name_plural': 'משתמשים'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=apps.accounts.models.UserRole.choices, default=apps.accounts.models.UserRole['USER'], max_length=20, verbose_name='תפקיד משתמש'),
        ),
    ]
