# Generated by Django 6.0.1 on 2026-02-03 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBBomTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DBComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('thickness', models.FloatField()),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('group', models.CharField(max_length=20)),
                ('component_type', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('global_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DBCustomizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('par1', models.FloatField()),
                ('par2', models.FloatField()),
                ('par3', models.FloatField()),
                ('par1_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DBCustomizerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DBOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DBProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sku', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBProductStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DBProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBBomComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(blank=True, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.dbbomtag')),
                ('DBComponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_boms', to='production.dbcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='DBComponentChanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('components_to_remove', models.ManyToManyField(blank=True, related_name='removed_by_changers', to='production.dbcomponent')),
                ('customizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.dbcustomizer')),
            ],
        ),
        migrations.CreateModel(
            name='DBComponentChangerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('qty', models.FloatField()),
                ('DBComponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.dbcomponent')),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_to_add', to='production.dbcomponentchanger')),
            ],
        ),
        migrations.AddField(
            model_name='dbcustomizer',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.dbcustomizertag'),
        ),
        migrations.CreateModel(
            name='DBOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('wall', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=10, null=True)),
                ('opening', models.CharField(blank=True, max_length=10, null=True)),
                ('undercut', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.dborder')),
            ],
        ),
        migrations.CreateModel(
            name='DBOrderItemCustomizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.dbcustomizer')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizers', to='production.dborderitem')),
            ],
        ),
        migrations.CreateModel(
            name='DBProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('global_type', models.CharField(max_length=1)),
                ('bom', models.ManyToManyField(related_name='bom', through='production.DBBomComponents', to='production.dbcomponent')),
                ('product_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.dbproductfamily')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.dbproducttype')),
            ],
        ),
        migrations.AddField(
            model_name='dborderitem',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.dbproductmodel'),
        ),
        migrations.AddField(
            model_name='dbcomponentchanger',
            name='product_models',
            field=models.ManyToManyField(related_name='component_changers', to='production.dbproductmodel'),
        ),
        migrations.AddField(
            model_name='dbbomcomponents',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_details', to='production.dbproductmodel'),
        ),
        migrations.AddField(
            model_name='dbproductfamily',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.dbproducttype'),
        ),
        migrations.CreateModel(
            name='DBFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.dbseries')),
            ],
        ),
    ]
