# Generated by Django 6.0.1 on 2026-01-29 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BomTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineMaterial',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.component')),
            ],
            bases=('production.component',),
        ),
        migrations.CreateModel(
            name='SheetMaterial',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.component')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('thickness', models.FloatField()),
                ('group', models.CharField(max_length=20)),
            ],
            bases=('production.component',),
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('panel_reduction_width', models.FloatField()),
                ('panel_reduction_height', models.FloatField()),
                ('double_door_gap', models.FloatField()),
                ('product_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productfamily')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.series')),
            ],
        ),
        migrations.CreateModel(
            name='Customizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModelBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.component')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productmodel')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.bomtags')),
            ],
        ),
        migrations.AddField(
            model_name='productfamily',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.producttype'),
        ),
    ]
