# Generated by Django 6.0.1 on 2026-02-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbcomponent',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dbproducttype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
