# Generated by Django 6.0.1 on 2026-01-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productfamily_name_alter_productmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmaterial',
            name='sheet_material_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetmaterial',
            name='sheet_material_sku',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
