# Generated by Django 6.0.1 on 2026-02-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_dbcomponent_color_alter_dbproducttype_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DBBomComponents',
            new_name='DBBomComponent',
        ),
    ]
