# Generated by Django 6.0.1 on 2026-02-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_rename_dbbomcomponents_dbbomcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dborder',
            name='customer',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
