# Generated by Django 6.0.1 on 2026-02-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_dborder_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbproductmodel',
            name='double_door_gap',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dbproductmodel',
            name='panel_reduction_height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dbproductmodel',
            name='panel_reduction_width',
            field=models.FloatField(default=0),
        ),
    ]
