# Generated by Django 6.0.1 on 2026-01-29 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productstages_linematerial_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizer',
            name='product_model',
        ),
        migrations.AddField(
            model_name='customizer',
            name='group',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customizer',
            name='par1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customizer',
            name='par2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customizer',
            name='par3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ComponentChanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('components_to_remove', models.ManyToManyField(blank=True, related_name='removed_by_changers', to='production.component')),
                ('customizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.customizer')),
                ('product_models', models.ManyToManyField(related_name='component_changers', to='production.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentChangerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('qty', models.FloatField()),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_to_add', to='production.componentchanger')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.component')),
            ],
        ),
    ]
