# Generated by Django 6.0.1 on 2026-02-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_dbproductmodel_double_door_gap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbcustomizer',
            name='par1',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dbcustomizer',
            name='par1_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dbcustomizer',
            name='par2',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dbcustomizer',
            name='par3',
            field=models.FloatField(blank=True),
        ),
    ]
