# Generated by Django 6.0.1 on 2026-01-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_remove_customizer_product_model_customizer_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodelbom',
            name='qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
