# Generated by Django 6.0.1 on 2026-01-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_productmodelbom_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('wall', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=10, null=True)),
                ('opening', models.CharField(blank=True, max_length=10, null=True)),
                ('undercut', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.order')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemCustomizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.customizer')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizers', to='production.orderitem')),
            ],
        ),
    ]
