# Generated by Django 6.0.1 on 2026-02-05 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_dbcustomizer_par1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbcomponentchangeritem',
            name='changer',
        ),
        migrations.RemoveField(
            model_name='dbcomponentchangeritem',
            name='DBComponent',
        ),
        migrations.AddField(
            model_name='dbcustomizer',
            name='components_to_remove',
            field=models.ManyToManyField(blank=True, related_name='removed_by_customizers', to='production.dbcomponent'),
        ),
        migrations.CreateModel(
            name='DBCustomizerComponentAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.dbcomponent')),
                ('customizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_components', to='production.dbcustomizer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.dbbomtag')),
            ],
        ),
        migrations.DeleteModel(
            name='DBComponentChanger',
        ),
        migrations.DeleteModel(
            name='DBComponentChangerItem',
        ),
    ]
