# Generated by Django 6.0.1 on 2026-02-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_remove_dbcomponentchangeritem_changer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbcustomizercomponentadd',
            name='product_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.dbproductmodel'),
        ),
        migrations.CreateModel(
            name='DBCustomizerComponentRemove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.dbcomponent')),
                ('customizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_components_v2', to='production.dbcustomizer')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.dbproductmodel')),
            ],
        ),
    ]
