# Generated by Django 6.0.1 on 2026-01-30 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_order_orderitem_orderitemcustomizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodelbom',
            name='sub_product_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_boms', to='production.productmodel'),
        ),
        migrations.AlterField(
            model_name='productmodelbom',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.component'),
        ),
        migrations.AlterField(
            model_name='productmodelbom',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='production.productmodel'),
        ),
    ]
