# Generated by Django 6.0.1 on 2026-02-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_dbcustomizercomponentadd_product_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbcustomizer',
            name='components_to_remove',
        ),
    ]
