# Generated by Django 6.0.1 on 2026-02-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_remove_dbcustomizer_components_to_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbcustomizercomponentremove',
            name='customizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_components', to='production.dbcustomizer'),
        ),
    ]
