# Generated by Django 6.0.3 on 2026-07-27 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('material_type', models.CharField(choices=[('SHEET', 'Sheet Material'), ('HARDWARE', 'Hardware / Accessories'), ('EDGE', 'Edge Banding')], default='SHEET', max_length=20, verbose_name='Material Type')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Thickness, mm')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Standard Length, mm')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Standard Width, mm')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price per unit')),
                ('unit_of_measure', models.CharField(default='pcs', max_length=20, verbose_name='Unit of Measure')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product Family',
                'verbose_name_plural': 'Product Families',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('base_material_thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Base Material Thickness, mm')),
                ('finished_thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Finished Product Thickness, mm')),
                ('parametric_rules', models.JSONField(blank=True, default=dict, verbose_name='Parametric Calculation & CNC Rules')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productfamily', verbose_name='Product Family')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.series', verbose_name='Series')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'unique_together': {('family', 'series')},
            },
        ),
        migrations.AddField(
            model_name='productfamily',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='catalog.producttype', verbose_name='Product Type'),
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_formula', models.CharField(default='1', help_text='Use variables like H (height), W (width), D (depth)', max_length=255, verbose_name='Consumption Formula')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Part / Component Note')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_products', to='catalog.material', verbose_name='Material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'BOM Item',
                'verbose_name_plural': 'BOM Items',
                'unique_together': {('product', 'material', 'note')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='productfamily',
            unique_together={('product_type', 'name')},
        ),
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code/SKU')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fronts', to='catalog.series', verbose_name='Series')),
            ],
            options={
                'verbose_name': 'Front',
                'verbose_name_plural': 'Fronts',
                'unique_together': {('series', 'name')},
            },
        ),
    ]
