# Generated by Django 6.0.3 on 2026-07-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfamily',
            name='code',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfamily',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='code',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='code',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(max_length=20, verbose_name='Material Type'),
        ),
    ]
