# Generated by Django 6.0.3 on 2026-08-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productfamily_code_productfamily_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='family',
            new_name='product_family',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_family', 'series')},
        ),
        migrations.AddField(
            model_name='front',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='front',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='series',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_material_thickness',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='finished_thickness',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parametric_rules',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
