# Generated by Django 6.0.3 on 2026-08-03 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_sku_product_code_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
        migrations.CreateModel(
            name='Customizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Уникальный код для быстрого поиска менеджером (напр. cmz1)', max_length=50, unique=True, verbose_name='Код / Артикул кастомайзера')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('tag', models.CharField(blank=True, db_index=True, help_text='Идентификатор стратегии обработки в коде (напр. LOCK_SELECTION)', max_length=100, null=True, verbose_name='Тег / Алгоритм')),
                ('priority', models.IntegerField(default=100, help_text='Порядок выполнения внутри фазы (чем меньше число, тем раньше выполняется)', verbose_name='Приоритет')),
                ('par1_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Параметр 1: Подпись')),
                ('par1_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр 1: Значение по умолчанию')),
                ('par1_hint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр 1: Подсказка')),
                ('par2_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Параметр 2: Подпись')),
                ('par2_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр 2: Значение по умолчанию')),
                ('par2_hint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр 2: Подсказка')),
                ('par3_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Параметр 3: Подпись')),
                ('par3_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр 3: Значение по умолчанию')),
                ('par3_hint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр 3: Подсказка')),
                ('par4_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Параметр 4: Подпись')),
                ('par4_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр 4: Значение по умолчанию')),
                ('par4_hint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр 4: Подсказка')),
                ('product_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizers', to='catalog.productfamily', verbose_name='Семейство продукции')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizers', to='catalog.productmodel', verbose_name='Модель продукции')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizers', to='catalog.producttype', verbose_name='Тип продукции')),
            ],
            options={
                'verbose_name': 'Кастомайзер / Опция',
                'verbose_name_plural': 'Кастомайзеры / Опции',
                'db_table': 'customizers',
                'ordering': ['priority', 'code'],
            },
        ),
    ]
