# Generated by Django 6.0.3 on 2026-08-05 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_product_productmodel_customizer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizer',
            options={'ordering': ['priority', 'code'], 'verbose_name': 'קסטומייזר / אפשרות', 'verbose_name_plural': 'קסטומייזרים / אפשרויות'},
        ),
        migrations.AlterModelOptions(
            name='front',
            options={'verbose_name': 'חזית', 'verbose_name_plural': 'חזיתות'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'חומר', 'verbose_name_plural': 'חומרים'},
        ),
        migrations.AlterModelOptions(
            name='productfamily',
            options={'verbose_name': 'משפחת מוצרים', 'verbose_name_plural': 'משפחות מוצרים'},
        ),
        migrations.AlterModelOptions(
            name='productmaterial',
            options={'verbose_name': 'פריט עץ מוצר', 'verbose_name_plural': 'פריטי עץ מוצר'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'מוצר', 'verbose_name_plural': 'מוצרים'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'סוג מוצר', 'verbose_name_plural': 'סוגי מוצרים'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'סדרה', 'verbose_name_plural': 'סדרות'},
        ),
        migrations.AlterField(
            model_name='customizer',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='פעיל'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='code',
            field=models.CharField(db_index=True, help_text='קוד ייחודי לחיפוש מהיר על ידי מנהל (למשל cmz1)', max_length=50, unique=True, verbose_name='קוד / מק""ט קסטומייזר'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='תיאור'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par1_hint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 1: רמז'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par1_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='פרמטר 1: תווית'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par1_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 1: ערך ברירת מחדל'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par2_hint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 2: רמז'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par2_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='פרמטר 2: תווית'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par2_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 2: ערך ברירת מחדל'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par3_hint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 3: רמז'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par3_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='פרמטר 3: תווית'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par3_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 3: ערך ברירת מחדל'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par4_hint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 4: רמז'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par4_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='פרמטר 4: תווית'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par4_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 4: ערך ברירת מחדל'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='priority',
            field=models.IntegerField(default=100, help_text='סדר ביצוע בתוך השלב (מספר קטן יותר מבוצע מוקדם יותר)', verbose_name='עדיפות'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='product_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizers', to='catalog.productfamily', verbose_name='משפחת מוצרים'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='product_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizers', to='catalog.productmodel', verbose_name='דגם מוצר'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizers', to='catalog.producttype', verbose_name='סוג מוצר'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='tag',
            field=models.CharField(blank=True, db_index=True, help_text='מזהה אסטרטגיית עיבוד בקוד (למשל LOCK_SELECTION)', max_length=100, null=True, verbose_name='תג / אלגוריתם'),
        ),
        migrations.AlterField(
            model_name='front',
            name='active',
            field=models.BooleanField(default=True, verbose_name='פעיל'),
        ),
        migrations.AlterField(
            model_name='front',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='קוד/SKU'),
        ),
        migrations.AlterField(
            model_name='front',
            name='description',
            field=models.TextField(blank=True, verbose_name='תיאור'),
        ),
        migrations.AlterField(
            model_name='front',
            name='name',
            field=models.CharField(max_length=100, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='front',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fronts', to='catalog.series', verbose_name='סדרה'),
        ),
        migrations.AlterField(
            model_name='material',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='אורך סטנדרטי, מ""מ'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(max_length=20, verbose_name='סוג חומר'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='מחיר ליחידה'),
        ),
        migrations.AlterField(
            model_name='material',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='מק""ט'),
        ),
        migrations.AlterField(
            model_name='material',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='עובי, מ""מ'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_of_measure',
            field=models.CharField(default='pcs', max_length=20, verbose_name='יחידת מידה'),
        ),
        migrations.AlterField(
            model_name='material',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='רוחב סטנדרטי, מ""מ'),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='active',
            field=models.BooleanField(default=True, verbose_name='פעיל'),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='קוד'),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='description',
            field=models.TextField(blank=True, verbose_name='תיאור'),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='name',
            field=models.CharField(max_length=100, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='catalog.producttype', verbose_name='סוג מוצר'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_products', to='catalog.material', verbose_name='חומר'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='הערת חלק / רכיב'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='catalog.productmodel', verbose_name='מוצר'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='quantity_formula',
            field=models.CharField(default='1', help_text='השתמש במשתנים כמו H (גובה), W (רוחב), D (עומק)', max_length=255, verbose_name='נוסחת צריכה'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='פעיל'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='מק""ט'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='תיאור'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productfamily', verbose_name='משפחת מוצרים'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.series', verbose_name='סדרה'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='active',
            field=models.BooleanField(default=True, verbose_name='פעיל'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='קוד'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='תיאור'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='series',
            name='active',
            field=models.BooleanField(default=True, verbose_name='פעיל'),
        ),
        migrations.AlterField(
            model_name='series',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='קוד'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, verbose_name='תיאור'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='שם'),
        ),
    ]
