# Generated by Django 6.0.3 on 2026-08-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_customizer_options_alter_front_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='has_door',
            field=models.BooleanField(default=True, verbose_name='יש דלת (Есть дверь)'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='has_frame',
            field=models.BooleanField(default=True, verbose_name='יש משקוף (Есть косяк)'),
        ),
    ]
