# Generated by Django 6.0.3 on 2026-08-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_producttype_has_door_producttype_has_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='קוד')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('active', models.BooleanField(default=True, verbose_name='פעיל')),
            ],
            options={
                'verbose_name': 'ידית',
                'verbose_name_plural': 'ידיות',
            },
        ),
    ]
