# Generated by Django 6.0.3 on 2026-08-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='שם')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='מק""ט')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='מחיר')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('active', models.BooleanField(default=True, verbose_name='פעיל')),
            ],
            options={
                'verbose_name': 'פרזול',
                'verbose_name_plural': 'פרזול',
            },
        ),
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
    ]
