# Generated by Django 6.0.3 on 2026-08-18 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_hardware_delete_productmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='קוד/גוון')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_colors', to='catalog.series', verbose_name='סדרה')),
            ],
            options={
                'verbose_name': 'צבע משקוף',
                'verbose_name_plural': 'צבעי משקופים',
                'ordering': ['id'],
                'unique_together': {('series', 'name')},
            },
        ),
    ]
