# Generated by Django 6.0.3 on 2026-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_populate_frame_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfamily',
            name='default_value_for_frame',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='עובי משקוף ברירת מחדל'),
        ),
    ]
