# Generated by Django 6.0.3 on 2026-08-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productfamily_default_value_for_frame'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='framecolor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='framecolor',
            name='series',
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='צבע'),
        ),
        migrations.AddField(
            model_name='material',
            name='common_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='שם רגיל'),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='קוד/גוון')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('active', models.BooleanField(default=True, verbose_name='פעיל')),
            ],
            options={
                'verbose_name': 'צבע משקוף',
                'verbose_name_plural': 'צבעי משקופים',
                'ordering': ['id'],
                'unique_together': {('id', 'name')},
            },
        ),
    ]
