# Generated by Django 6.0.3 on 2026-08-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_framecolor_unique_together_and_more'),
        ('orders', '0023_alter_order_basic_color_frames_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrameColor',
        ),
    ]
