# Generated by Django 6.0.3 on 2026-08-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_material_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.color'),
        ),
    ]
