# Generated by Django 6.0.3 on 2026-08-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_material_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizer',
            name='strategy',
            field=models.IntegerField(choices=[(0, 'ללא אסטרטגיה'), (1, 'אסטרטגיה 1'), (2, 'אסטרטגיה 2'), (3, 'אסטרטגיה 3'), (4, 'אסטרטגיה 4'), (5, 'אסטרטגיה 5'), (6, 'אסטרטגיה 6'), (7, 'אסטרטגיה 7'), (8, 'אסטרטגיה 8'), (9, 'אסטרטגיה 9'), (10, 'אסטרטגיה 10 (Frames Report)')], default=0, help_text='שלב עיבוד שבו התוספת משתתפת', verbose_name='אסטרטגיה'),
        ),
    ]
