# Generated by Django 6.0.3 on 2026-09-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_customizer_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizer',
            name='par5_hint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר5: רמז'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='par5_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='פרמטר 5: תווית'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='par5_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 5: ערך ברירת מחדל'),
        ),
    ]
