# Generated by Django 6.0.3 on 2026-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_customizer_par5_hint_customizer_par5_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizer',
            name='hardwares',
            field=models.ManyToManyField(blank=True, help_text='רכיבי פרזול להחלפה או הוספה במפרט הטכני', related_name='customizers', to='catalog.hardware', verbose_name='פרזול (Hardware)'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='materials',
            field=models.ManyToManyField(blank=True, help_text='חומרים להחלפה או הוספה במפרט הטכני', related_name='customizers', to='catalog.material', verbose_name='חומרים (Material)'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='tag',
            field=models.CharField(blank=True, db_index=True, help_text='מזהה אסטרטגיית עיבוד בקוד', max_length=100, null=True, verbose_name='תג / אלגוריתם'),
        ),
    ]
