# Generated by Django 6.0.3 on 2026-09-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_customizer_hardwares_customizer_materials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customizer',
            old_name='hardwares',
            new_name='hardware_list',
        ),
    ]
