# Generated by Django 6.0.3 on 2026-09-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_rename_hardwares_customizer_hardware_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizer',
            options={'ordering': ['tag', 'code'], 'verbose_name': 'קסטומייזר / אפשרות', 'verbose_name_plural': 'קסטומייזרים / אפשרויות'},
        ),
        migrations.RemoveField(
            model_name='customizer',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='customizer',
            name='strategy',
        ),
        migrations.AlterField(
            model_name='customizer',
            name='tag',
            field=models.CharField(db_index=True, default='none', help_text='מזהה אסטרטגיית עיבוד בקוד', max_length=100, verbose_name='תג / אלגוריתם'),
        ),
    ]
