# Generated by Django 6.0.3 on 2026-09-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_customizer_options_remove_customizer_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizer',
            name='tag',
            field=models.CharField(db_index=True, help_text='מזהה אסטרטגיית עיבוד בקוד', max_length=100, verbose_name='תג / אלגוריתם'),
        ),
    ]
