# Generated by Django 6.0.3 on 2026-09-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_customizer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizer',
            name='par1_options',
            field=models.TextField(blank=True, help_text='KEY:LABEL or SKU:LABEL separated by commas (e.g., hrdw121-12: חצי קומפקט, hrdw100: רגיל or CYLINDER:צילינדר, WC:תפוס/פנוי)', null=True, verbose_name='פרמטר 1: אפשרויות'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='par2_options',
            field=models.TextField(blank=True, help_text='KEY:LABEL or SKU:LABEL separated by commas (e.g., hrdw121-12: חצי קומפקט, hrdw100: רגיל or CYLINDER:צילינדר, WC:תפוס/פנוי)', null=True, verbose_name='פרמטר 2: אפשרויות'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='par3_options',
            field=models.TextField(blank=True, help_text='KEY:LABEL or SKU:LABEL separated by commas (e.g., hrdw121-12: חצי קומפקט, hrdw100: רגיל or CYLINDER:צילינדר, WC:תפוס/פנוי)', null=True, verbose_name='פרמטר 3: אפשרויות'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='par4_options',
            field=models.TextField(blank=True, help_text='KEY:LABEL or SKU:LABEL separated by commas (e.g., hrdw121-12: חצי קומפקט, hrdw100: רגיל or CYLINDER:צילינדר, WC:תפוס/פנוי)', null=True, verbose_name='פרמטר 4: אפשרויות'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='par5_options',
            field=models.TextField(blank=True, help_text='KEY:LABEL or SKU:LABEL separated by commas (e.g., hrdw121-12: חצי קומפקט, hrdw100: רגיל or CYLINDER:צילינדר, WC:תפוס/פנוי)', null=True, verbose_name='פרמטר 5: אפשרויות'),
        ),
    ]
