# Generated by Django 6.0.3 on 2026-09-07 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_customizer_par1_options_customizer_par2_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizer',
            name='product_family',
        ),
        migrations.RemoveField(
            model_name='customizer',
            name='product_model',
        ),
        migrations.RemoveField(
            model_name='customizer',
            name='product_type',
        ),
        migrations.AddField(
            model_name='customizer',
            name='primary_hardware',
            field=models.ForeignKey(blank=True, help_text='קישור ישיר לפריט במחסן להזמנה אוטומטית', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_customizers', to='catalog.hardware', verbose_name='פרזול ראשי (Warehouse Hardware)'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='product_families',
            field=models.ManyToManyField(blank=True, related_name='customizers', to='catalog.productfamily', verbose_name='משפחות מוצרים'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='product_models',
            field=models.ManyToManyField(blank=True, related_name='customizers', to='catalog.productmodel', verbose_name='דגמי מוצרים'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='product_types',
            field=models.ManyToManyField(blank=True, related_name='customizers', to='catalog.producttype', verbose_name='סוגי מוצרים'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='product_families',
            field=models.ManyToManyField(blank=True, related_name='hardware_items', to='catalog.productfamily', verbose_name='משפחות מוצרים'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='product_models',
            field=models.ManyToManyField(blank=True, related_name='hardware_items', to='catalog.productmodel', verbose_name='דגמי מוצרים'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='product_types',
            field=models.ManyToManyField(blank=True, related_name='hardware_items', to='catalog.producttype', verbose_name='סוגי מוצרים'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par1_options',
            field=models.TextField(blank=True, help_text='Options separated by commas. Use SKU=prefix:LABEL for inventory (e.g. SKU=hrdw121-12: צילינדר) or KEY:LABEL for generic values (e.g. NONE: ללא, WC: תפוס/פנוי).', null=True, verbose_name='פרמטר 1: אפשרויות'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par2_options',
            field=models.TextField(blank=True, help_text='Options separated by commas. Use SKU=prefix:LABEL for inventory (e.g. SKU=hrdw121-12: צילינדר) or KEY:LABEL for generic values (e.g. NONE: ללא, WC: תפוס/פנוי).', null=True, verbose_name='פרמטר 2: אפשרויות'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par3_options',
            field=models.TextField(blank=True, help_text='Options separated by commas. Use SKU=prefix:LABEL for inventory (e.g. SKU=hrdw121-12: צילינדר) or KEY:LABEL for generic values (e.g. NONE: ללא, WC: תפוס/פנוי).', null=True, verbose_name='פרמטר 3: אפשרויות'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par4_options',
            field=models.TextField(blank=True, help_text='Options separated by commas. Use SKU=prefix:LABEL for inventory (e.g. SKU=hrdw121-12: צילינדר) or KEY:LABEL for generic values (e.g. NONE: ללא, WC: תפוס/פנוי).', null=True, verbose_name='פרמטר 4: אפשרויות'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par5_options',
            field=models.TextField(blank=True, help_text='Options separated by commas. Use SKU=prefix:LABEL for inventory (e.g. SKU=hrdw121-12: צילינדר) or KEY:LABEL for generic values (e.g. NONE: ללא, WC: תפוס/פנוי).', null=True, verbose_name='פרמטר 5: אפשרויות'),
        ),
    ]
