# Generated by Django 6.0.3 on 2026-09-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_remove_customizer_product_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizer',
            name='hardware_list',
        ),
        migrations.RemoveField(
            model_name='customizer',
            name='primary_hardware',
        ),
        migrations.AddField(
            model_name='customizer',
            name='hardware',
            field=models.ForeignKey(blank=True, help_text='קישור ישיר לפריט במחסן להזמנה אוטומטית', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizers', to='catalog.hardware', verbose_name='פרזול (Hardware)'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='components',
            field=models.ManyToManyField(blank=True, help_text='Components that make up this assembly', related_name='assembled_in', to='catalog.hardware', verbose_name='רכיבים (Components)'),
        ),
    ]
