# Generated by Django 6.0.3 on 2026-09-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_remove_customizer_hardware_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('outward_substitute', models.ForeignKey(blank=True, help_text='Substitution geometry when opening direction is OUT.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward_counterparts', to='catalog.profilegeometry', verbose_name='Outward Opening Substitute')),
            ],
            options={
                'verbose_name': 'Profile Geometry',
                'verbose_name_plural': 'Profile Geometries',
            },
        ),
        migrations.AddField(
            model_name='customizer',
            name='profile_geometry',
            field=models.ForeignKey(blank=True, help_text='Overrides physical profile geometry (e.g., N60 -> N8)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizers', to='catalog.profilegeometry', verbose_name='Profile Geometry'),
        ),
        migrations.AddField(
            model_name='material',
            name='profile_geometry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='catalog.profilegeometry', verbose_name='Profile Geometry'),
        ),
    ]
