# Generated by Django 6.0.3 on 2026-09-09 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_profilegeometry_customizer_profile_geometry_and_more'),
        ('production', '0016_remove_bom_frame_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizer',
            name='profile_geometry',
        ),
        migrations.RemoveField(
            model_name='material',
            name='profile_geometry',
        ),
        migrations.AddField(
            model_name='material',
            name='outward_substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward_originals', to='catalog.material', verbose_name='תחליף לפתיחה החוצה'),
        ),
        migrations.DeleteModel(
            name='ProfileGeometry',
        ),
    ]
