# Generated by Django 6.0.3 on 2026-09-09 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_remove_customizer_profile_geometry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfamily',
            name='leaf_height_adjustment',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='תיקון גובה כנף (Корректировка высоты полотна)'),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='leaf_width_adjustment',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='תיקון רוחב כנף (Корректировка ширины полотна)'),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='thickness',
            field=models.FloatField(default=0.0, verbose_name='עובי (Толщина)'),
        ),
    ]
