# Generated by Django 6.0.3 on 2026-09-09 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_productfamily_leaf_height_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizer',
            name='requires_door',
            field=models.BooleanField(default=False, verbose_name='דורש כנף (Требует полотно)'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='requires_frame',
            field=models.BooleanField(default=False, verbose_name='דורש משקוף (Требует коробку)'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='has_door',
            field=models.BooleanField(default=True, verbose_name='יש דלת (Есть полотно)'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='has_frame',
            field=models.BooleanField(default=True, verbose_name='יש משקוף (Есть коробка)'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='parent_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_models', to='catalog.productmodel', verbose_name='דגם אב'),
        ),
    ]
