# Generated by Django 6.0.3 on 2026-09-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_customizer_requires_door_customizer_requires_frame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizer',
            name='requires_door',
        ),
        migrations.RemoveField(
            model_name='customizer',
            name='requires_frame',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='has_door',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='has_frame',
        ),
    ]
