# Generated by Django 6.0.3 on 2026-09-10 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_remove_customizer_requires_door_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfamily',
            name='double_leaf_overlap',
            field=models.FloatField(default=0.7, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='תנקון מידה לדלת כפולה'),
        ),
    ]
