# Generated by Django 6.0.3 on 2026-09-14 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_productfamily_double_leaf_overlap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfamily',
            name='leaf_height_adjustment',
        ),
        migrations.RemoveField(
            model_name='productfamily',
            name='leaf_width_adjustment',
        ),
        migrations.AddField(
            model_name='productfamily',
            name='frame_inner_height_reduction',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='הפחתת גובה פתח משקוף'),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='frame_inner_width_reduction',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='הפחתת רוחב פתח משקוף'),
        ),
    ]
