# Generated by Django 6.0.3 on 2026-09-14 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_remove_productfamily_leaf_height_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfamily',
            name='leaf_height_clearance',
            field=models.FloatField(default=-1.0, help_text='Суммарный зазор полотна по высоте (пол + верх) (в мм)', validators=[django.core.validators.MaxValueValidator(0.0)], verbose_name='מרווח גובה כנף (Зазор высоты полотна)'),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='leaf_side_clearance',
            field=models.FloatField(default=-0.7, help_text='Зазор полотна на каждую сторону (в мм)', validators=[django.core.validators.MaxValueValidator(0.0)], verbose_name='מרווח צד כנף (Зазор полотна на сторону)'),
        ),
    ]
