# Generated by Django 6.0.3 on 2026-09-14 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_productfamily_leaf_height_clearance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfamily',
            name='leaf_height_clearance',
        ),
        migrations.AddField(
            model_name='productfamily',
            name='leaf_bottom_clearance',
            field=models.FloatField(default=-1.0, help_text='Суммарный зазор полотна по высоте (пол) (в мм)', validators=[django.core.validators.MaxValueValidator(0.0)], verbose_name='מרווח תחתון כנף'),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='leaf_top_clearance',
            field=models.FloatField(default=-1.0, help_text='Суммарный зазор полотна по высоте (верх) (в мм)', validators=[django.core.validators.MaxValueValidator(0.0)], verbose_name='מרווח עליון כנף'),
        ),
    ]
