# Generated by Django 6.0.3 on 2026-09-20 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_remove_productfamily_leaf_height_clearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizer',
            name='is_required',
            field=models.BooleanField(default=False, help_text='אם מסומן, קסטומייזר זה יצורף אוטומטית לקבוצה ויידרש במעבר לייצור', verbose_name='חובה (אוטומטי לקבוצה)'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='par1_required',
            field=models.BooleanField(default=False, verbose_name='פרמטר 1: שדה חובה'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='par2_required',
            field=models.BooleanField(default=False, verbose_name='פרמטר 2: שדה חובה'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='par3_required',
            field=models.BooleanField(default=False, verbose_name='פרמטר 3: שדה חובה'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='par4_required',
            field=models.BooleanField(default=False, verbose_name='פרמטר 4: שדה חובה'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='par5_required',
            field=models.BooleanField(default=False, verbose_name='פרמטר 5: שדה חובה'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='required_customizers',
            field=models.ManyToManyField(blank=True, related_name='required_for_products', to='catalog.customizer', verbose_name='קסטומייזרים חובה'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='par5_hint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='פרמטר 5: רמז'),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='leaf_bottom_clearance',
            field=models.FloatField(default=-1.0, help_text='зазор полотна по высоте (пол) (в мм)', validators=[django.core.validators.MaxValueValidator(0.0)], verbose_name='מרווח תחתון כנף'),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='leaf_side_clearance',
            field=models.FloatField(default=-0.7, help_text='Суммарный Зазор полотна на обе стороны (в мм)', validators=[django.core.validators.MaxValueValidator(0.0)], verbose_name='מרווח צדדים כנף (Суммарный Зазор полотна на обе стороны)'),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='leaf_top_clearance',
            field=models.FloatField(default=-1.0, help_text='зазор полотна по высоте (верх) (в мм)', validators=[django.core.validators.MaxValueValidator(0.0)], verbose_name='מרווח עליון כנף'),
        ),
    ]
