# Generated by Django 6.0.3 on 2026-09-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_customizer_is_required_customizer_par1_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='allowed_direction',
            field=models.CharField(choices=[('BOTH', 'Both directions (In / Out)'), ('IN_ONLY', 'Inward only (In)'), ('OUT_ONLY', 'Outward only (Out)')], default='BOTH', help_text='Limits allowed door opening direction for this model', max_length=10, verbose_name='Allowed opening direction'),
        ),
    ]
